version: '3.7'

services:
  
  mongo-admin:
    image: mongo:latest
    volumes:
      - ./mongodb/seed:/docker-entrypoint-initdb.d
      - YOUR/PATH/mongo/db:/data/db
      - YOUR/PATH/mongo/backup:/data/backup
    environment:
      MONGO_INITDB_DATABASE: lintoAdminV2
    networks:
      - linto-net
      - internal

  linto-admin:
    image: linto-admin-v2:latest
    build: .
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    env_file: .docker_env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - linto-net
      - internal

  redis-admin:
    image: redis:latest
    networks:
      - internal

networks:
  linto-net:
    external: true
  internal:
